# Empty listen_addresses to use systemd socket activation
listen_addresses = ['127.0.0.1:5353']
server_names = ['cloudflare-security']
#server_names = ['cloudflare']

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blocklist (for parental control, ads blocking...)
require_nofilter = true

#bootstrap_resolvers = ['1.1.1.1:53']
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '1.1.1.1:53'

[query_log]
  file = '/var/log/query.log'

[nx_log]
  file = '/var/log/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/config/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''